# Generated by Django 3.2.11 on 2024-05-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_quantity_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_available',
        ),
    ]
