# Generated by Django 3.2.11 on 2024-05-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_ordered', 'Not Ordered'), ('complete', 'Complete'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not_ordered', max_length=20),
        ),
    ]
