# Generated by Django 3.2.11 on 2024-05-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20240531_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='order_item',
        ),
        migrations.AddField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='order',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
            preserve_default=False,
        ),
    ]
