# Generated by Django 3.2.11 on 2024-05-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20240531_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Return',
            new_name='Refund',
        ),
    ]
