# Generated by Django 5.0.6 on 2024-06-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_refunditem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunditem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
