# Generated by Django 5.0.6 on 2024-06-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_refunditem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_discount_free_items',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_discount_threshold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
