# Generated by Django 5.0.6 on 2024-06-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_orderitem_is_free_product_bulk_discount_free_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='related_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_items', to='store.orderitem'),
        ),
    ]
