# Generated by Django 5.0.6 on 2024-06-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_orderitem_is_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunditem',
            name='refund_amount',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
