# Generated by Django 5.0.6 on 2024-06-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('no_refund', 'No_refund'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='no_refund', max_length=20),
        ),
    ]
