# Generated by Django 5.0.6 on 2024-06-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_item_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_item', to='store.product'),
        ),
    ]
